### ISSUE TITLE
PSDを理解する

### ISSUE THREAD

**Issue by shokkunrf** [shokkunrf/resd#1]
https://www.adobe.com/devnet-apps/photoshop/fileformatashtml

**Comment by takenokoroid** [comment]
サンプル
https://oov.github.io/psdtool/

**Comment by takenokoroid** [comment]
8BIM luniあたりにUTF-16でレイヤー名が書いてある
![image](https://user-images.githubusercontent.com/52944041/178743082-ab5d421a-9d5a-4b5f-898d-59bb15dd8e02.png)
「(´･ω･`)」が書いてある

**Comment by takenokoroid** [comment]
文字コード参考
http://ash.jp/code/unitbl21.htm

**Comment by takenokoroid** [comment]
文字を追加するとどんな変化が起こるのか知りたい
sasara1.psdとsasara2.psdを使ってDiffをとる
ただHex Editorの都合上Diffをとることが難しいため、ヘッダーからバイナリをみていくことに

名前,開始,確保バイナリ（byte）
~~File Header,0000 0000,26byte,~~
~~Color Mode Data,0000 000F ,1024byte~~
~~Image Resources,0000 020F,61938byte~~
~~Layer and Mask,,~~

僕たちが2byteだと思ってたのは1byteだった！！
振り出しに戻る

**Comment by takenokoroid** [comment]
sasara2.psd

| セクション | 開始位置 | 終了位置 | バイナリサイズ(bytes) |
| --- | --- | --- |
| File Header | 0000 0000 | 26 | 26 |
| ColorMode | 0000 001A | 26 | 4 + 0 |
| Image Resources | 0000 001E | 26 | 4 + 2048 |
| Layer and Mask |  |  |
| Image Data | |  |

**Comment by shokkunrf** [comment]
https://github.com/shokkunrf/resd/wiki/sasara2.psd に移動
